[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.59"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  branch = "master"
  name = "github.com/marcinwyszynski/ssmvars"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "1.3.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
